image: "crystallang/crystal:latest"

before_script:
  - shards install

spec:
  stage: test
  script: crystal spec

pages:
  needs:
    - spec
  script:
    - apt-get update -y
    - add-apt-repository ppa:deadsnakes/ppa
    - apt-get install -y python3.8
    - make build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"